blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/fabiobrunning/neo-design-system/wiki
    about: Check our documentation before opening an issue
  - name: Discussions
    url: https://github.com/fabiobrunning/neo-design-system/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
